name: ci_cd_week1

on:
  push:
    branches:
      - 'master'

env:
  IMAGE_SIMLESERVER =

jobs:
  build_and_push-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: action/checkout@v2

      - name: login_to_docker_hub
      - uses: docker/login-action@v1
      with:
        username: 'lyabomyr'
        password: 'lyabomyr1111'


    - name: set up docker build
      uses: dicker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@2
      with:
        context: .
        file:  Dockerfile
        push: true
        tags: lyabomyr/${{env.IMAGE_SIMLESERVER}}:latest
        cache-from: type=registry, ref=lyabomyr/${{env.IMAGE_SIMLESERVER}}:buildcache
        cache-to: type = registry, ref=lyabomyr/${{env.IMAGE_SIMLESERVER}}:buildcache,mode=max
