apiVersion: batch/v1
kind: Job
metadata:
  name: job-ml
spec:
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: lyabomyr/server_ml:latest
          name: job-ml
