apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app : week5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: fastapi-app
  template:
    metadata:
      labels:
        project: fastapi-app
    spec:
      containers:
        - name : api-container
          image: lyabomyr/app-fastapi:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    env  : week5
    owner: liubomyr
spec:
  selector:
    project: fastapi-app
  ports:
    - name      : fastapi-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8080
  type: LoadBalancer