apiVersion : apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app : my-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: streamlit-app
  template:
    metadata:
      labels:
        project: streamlit-app
    spec:
      containers:
        - name : streamlit-container
          image: lyabomyr/app-streamlit:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    env  : week5
    owner: liubomyr
spec:
  selector:
    project: streamlit-app
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8080
  type: LoadBalancer