name: ci_cd_week1

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'week2'
env:
  IMAGE_SIMLESERVER: server_ml

jobs:
  build_and_push-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: login_to_docker_hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.LOGIN_DOCKER_HUB}}
          password: ${{secrets.PASSWORD_DOCKER_HUB}}


      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file:  Dockerfile
          push: true
          tags: ${{secrets.LOGIN_DOCKER_HUB}}/${{env.IMAGE_SIMLESERVER}}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push-ml]
    steps:
    - name: docker deploy
      run: |
        echo 'will be add in futher implementation'
    

  k8s_local_test_with_minikube:

    runs-on: ubuntu-latest
    name: build example and deploy to minikube

    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Deploy job to minikube
      run: |
        kubectl create -f k8s-resources/job-ml.yaml 
        #kubectl wait --for=condition=complete --timeout=300s job/job-ml
        kubectl get pod
    - name: Deploy app to minikube
      run: |
        kubectl get pod 
