name: week5
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'week5'
      - 'week_5'
env:
  IMAGE_SIMLESERVER: docker_file_for_serving

jobs:
  build_and_push-project_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: login_to_docker_hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.LOGIN_DOCKER_HUB}}
          password: ${{secrets.PASSWORD_DOCKER_HUB}}


      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file:  week5/Dockerfile
          push: true
          tags: ${{secrets.LOGIN_DOCKER_HUB}}/${{env.IMAGE_SIMLESERVER}}:latest

      - name: Docker Run Action
        uses: addnab/docker-run-action@v3
        with:
          image: ${{secrets.LOGIN_DOCKER_HUB}}/${{env.IMAGE_SIMLESERVER}}:latest
          run: |
            pytest unit_tests/test_fastapi.py